### ISSUE TITLE
Synchronization issue with AR overlays

### ISSUE THREAD

**Issue by cerspense** [TouchDesigner/TouchEngine-UE4#64]
I am observing a 1 frame delay between data in Unreal and Touch Engine when using the Synchronized cook mode. This was tested with sending camera data and sequenced, keyframed data into Touch Engine. Changing the cook mode to Independent 120 seems to remedy the issue. Video documentation and project file are located here: https://www.dropbox.com/sh/iwa3gbmatx1jxo3/AAA_p3GEKHsP0f0bzwT-suwia?dl=0

**Comment by ddthejj** [comment]
Should be fixed in 39a6880f58d8ff0874fe08285eb34e3a2526352e (MegaNode branch)

**Comment by ddthejj** [comment]
Fixed in 22e04242a86d9a0449f19b3e5567becb9719fb2b of Samples branch

**Comment by jetXS** [comment]
Difficult to tell at the moment with how fast colors are blinking / changing. My guess is that we are not there yet.

Last commit referring to Sync was statin

"Synchronized mode should be closer to frame synced, **but not quite**"

Can you have another look and see what can be improved ?

Thanks

**Comment by RVillani** [comment]
After further investigation, it turns out the issue has been fixed for a while.

The user’s Blueprint was setting TouchEngine variables and then reading its outputs on the same frame, during an Unreal Tick. Back in the date of the OP, there was no way to make TouchEngine cook the frame right in between those two calls, so the user would always see the result from the variables set on the previously cooked frame, explaining the 1-frame delay.

On May 25th 2021, the delegates `SetInputs` and `GetOutputs` were added to `UTouchEngineComponent`, on commit https://github.com/TouchDesigner/TouchEngine-UE/commit/628fa50d1ae166e73fa7b87d58fcfad0b0ede47b. Those allow users to set variables before cook and get the output right after it was completed, effectively fixing this issue.

Since then, it’s possible to have 1:1 synchronization with TouchEngine cooked frames. Be aware, however, that TouchEngine won’t update its cooked frame faster than its set frame rate, so it should have a frame rate at least as fast as Unreal’s for changes to be seen on every Unreal frame.

On December 10th 2021, the commit https://github.com/TouchDesigner/TouchEngine-UE-Samples/commit/22e04242a86d9a0449f19b3e5567becb9719fb2b updated the SyncTest sample Blueprint to show how to use those delegates.

The commit https://github.com/TouchDesigner/TouchEngine-UE-Samples/commit/486257c34673efb8b724a2d284ce10596875b3ac, on the 5.0 branch, makes the effect clearer. Numbered textures are switched every frame and if TouchEngine’s frame rate is lower than Unreal’s, a tear can be seen in the middle of the cube, from the difference between the top texture set by Unreal and the bottom one, returned by TouchEngine. This commit also raises the TouchEngine frame rate of the SyncTest sample to 121, to ensure it's always higher than the default max of 120 fps in the Unreal Engine 5 editor, guaranteeing a visible texture change from TouchEngine on each Unreal Engine frame.
